server:
  port: 8081
  error:
    include-message: always

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        
management:
  endpoints:
    web:
      exposure:
        include: "*"