server:
  port: 0

spring:
  application:
    name: appointment-service
  datasource:
    url: jdbc:mysql://localhost:3307/appointment_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 60000

  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 1000
